chore: Initialize install script to install and bootstrap nt-connect
NorthernTechHQ/nt-connect pull request #45
Opened 2024-01-25 14:58 UTC by alfrunes

2024-01-31 09:30 UTC, kjaskiewiczz approved these changes
I'm not a bash expert, but it looks good to me

2024-02-01 13:27 UTC, olehermanse requested changes
I tested it and it works! 🚀 

A couple of things to fix:

1. If you don't have jq installed the script does not handle this nicely. Ideally I'd try to get rid of the dependency. Optionally check for jq, and print a nice error message.
2. Once that happened, it left /etc/nt-connect in a bad state and the script didn't work any more;

```
ERRO[2024-02-01T13:23:21Z] Error loading configuration from file: /etc/nt-connect/nt-connect.json (Error parsing nt-connect configuration file: unexpected end of JSON input) 
ERRO[2024-02-01T13:23:21Z] Error parsing nt-connect configuration file: unexpected end of JSON input 
```

What's the desired behavior of running this script when `/etc/nt-connect` already exists?

2024-02-01 13:36 UTC, alfrunes commented
> A couple of things to fix:
> 
> 1. If you don't have jq installed the script does not handle this nicely. Ideally I'd try to get rid of the dependency. Optionally check for jq, and print a nice error message.

`jq` is required when bootstrapping the configuration. There's also `curl` and (optionally) `systemctl` dependencies here. I'll improve the error handling for the cases where any of these are missing.

> 2. Once that happened, it left /etc/nt-connect in a bad state and the script didn't work any more;
> 
> ```
> ERRO[2024-02-01T13:23:21Z] Error loading configuration from file: /etc/nt-connect/nt-connect.json (Error parsing nt-connect configuration file: unexpected end of JSON input) 
> ERRO[2024-02-01T13:23:21Z] Error parsing nt-connect configuration file: unexpected end of JSON input 
> ```

Ouch! That's not supposed to happen.

> What's the desired behavior of running this script when `/etc/nt-connect` already exists?

The script will not attempt to overwrite any existing files except for the binary itself. It will, however, attempt to inject the tenant token into the configuration file.

2024-02-02 14:06 UTC, olehermanse commented on support/install.sh
> +	if test -x /sbin/systemctl; then
On my VM it's `/usr/bin/systemctl`, so this did not work. Might want to check `which systemctl` or something similar.

2024-02-02 14:36 UTC, olehermanse commented on support/install.sh
> +		echo "To start the daemon, run:"
A little bit more of a warning would have helped me here:

```suggestion
		echo "Warning: nt-connect is not running - did not find systemctl(!)"
		echo "To start the daemon, run:"
```

2024-02-02 16:33 UTC, olehermanse approved these changes
Tested again, looks good :)

2024-02-05 03:57 UTC, merged